name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub (or any other registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_USER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER_NAME }}/utilities:${{ github.sha }} .

      # Push the Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USER_NAME }}/utilities:${{ github.sha }}

      # (Optional) Tag the image with a version or latest
      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.DOCKER_USER_NAME }}/utilities:${{ github.sha }} ${{ secrets.DOCKER_USER_NAME }}/utilities:latest
          docker push ${{ secrets.DOCKER_USER_NAME }}/utilities:latest
